---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: false
  fixme:
    enabled: false
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.php"
exclude_paths:
- e107_handlers/hybridauth/**/*
- e107_handlers/jsshrink/**/*
- e107_handlers/phpmailer/**/*
- e107_handlers/phpthumb/**/*
- e107_web/**/*

