---

# Path (absolute or relative) to the app intended to be tested
# Absolute path begins with "/"; relative path does not begin with "/"
app_path: 'e107/'

# Configure this section to customize the database populator
db_dump:

  # If set to true, the populator will populate the database with the dump specified in the "path" key
  # If set to false, the test database needs to be set up separately
  # Affects all modes of deployment
  enabled: true

  # Path (absolute or relative) to the database dump of a testable installation of the app
  # Absolute path begins with "/"; relative path does not begin with "/"
  path: 'tests/_data/e107_v2.1.8.sample.sql'

# Configure this section for automated test deployments to cPanel
cpanel:

  # If set to true, this section takes precedence over the "manual" section.
  enabled: false

  # cPanel domain without the port number
  hostname: ''

  # cPanel account username
  username: ''

  # cPanel account password
  password: ''


# Configure this section for manual test deployments
manual:

  # URL to the app that you deployed manually; needed for acceptance tests
  url: 'http://set-this-if-running-acceptance-tests-manually.local'

  # Only MySQL/MariaDB is supported
  db:
    # Hostname or IP address; use 'localhost' for a local server
    host: 'set-this-if-running-tests-manually.local'

    # Port number of the server
    port: '3306'

    # Database name; must exist already
    dbname: 'e107'

    # Username; must exist already
    user: 'root'

    # Password; set to blank string for no password
    password: ''
